server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&verifyServerCertificate=false&serverTimezone=UTC
    username: root
    password: 123321
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis 配置
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 50
        max-idle: 10
        min-idle: 5
        max-wait: 200ms
    jedis:
      pool:
        max-active: 50
        max-idle: 10
        min-idle: 5
        max-wait: 10000ms
  servlet:
    multipart:
      max-file-size: 10MB
mybatis-plus:
  configuration:
    # myBatis 配置
    map-underscore-to-camel-case: false
    # 日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl